--Apply to AZWildfires.sqlite
 DROP TABLE az_wildfires;
 DROP TABLE az_droughts;
 
 CREATE TABLE az_wildfires (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  FIRE_NAME TEXT(255) NOT NULL,
  FIRE_YEAR INTEGER NOT NULL,
  DISCOVERY_TIME TEXT(255) NOT NULL,
  CONT_TIME TEXT(255) NOT NULL,
  STAT_CAUSE_CODE REAL NOT NULL,
  STAT_CAUSE_DESCR TEXT(100) NOT NULL,
  FIRE_SIZE REAL NOT NULL,
  FIRE_SIZE_CLASS TEXT(1) NOT NULL,
  LATITUDE REAL NOT NULL,
  LONGITUDE REAL NOT NULL,
  OWNER_CODE REAL NOT NULL,
  OWNER_DESCR TEXT(100) NOT NULL,
  STATE TEXT(255) NOT NULL,
  COUNTY TEXT(255) NOT NULL,
  fire_discovery_date TEXT(255) NOT NULL,
  fire_cont_date TEXT(255) NOT NULL
);

CREATE TABLE az_droughts (
  ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  County TEXT(255) NOT NULL,
  State TEXT(255) NOT NULL,
  Year INTEGER NOT NULL,
  Count INTEGER NOT NULL,
  Condition TEXT(255) NOT NULL
);
